version: '3.9'
services:
  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - telegram-bot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ${PWD}/certbot/www:/var/www/certbot/:ro
      - ${PWD}/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - bot
    restart: always
    healthcheck:
      test: curl --fail http://0.0.0.0:5000/info || exit 1
      interval: 1m
      retries: 5
      timeout: 10s
      start_period: 40s

  telegram-bot:
    container_name: ggl_bot_webhook
    build:
      context: .
      dockerfile: Dockerfile.webhook
    restart: always
    volumes:
      - ${PWD}/logs:/code/logs/
    env_file:
      - .env
    networks:
      - bot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ${PWD}/certbot/www/:/var/www/certbot/:rw
      - ${PWD}/certbot/conf/:/etc/letsencrypt/:rw

networks:
  bot:
    driver: "bridge"
