version: '3.9'
services:
  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - telegram-bot
    ports:
      - "8082:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - bot

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - ./logs:/code/logs/
    env_file:
      - .env
    networks:
      - bot

networks:
  bot:
    driver: "bridge"