version: '3.9'
services:
  telegram-bot:
    container_name: ggl_bot_polling
    build:
      context: .
      dockerfile: Dockerfile.polling
    restart: always
    volumes:
      - ${PWD}/logs:/code/logs/
    env_file:
      - .env
    networks:
      - bot
    healthcheck:
      test: curl --fail https://api.telegram.org/bot${BOT_TOKEN}/getMe || exit 1
      interval: 1m
      retries: 5
      timeout: 10s
      start_period: 20s


networks:
  bot:
    driver: "bridge"
