FROM python:3.10-slim-buster
LABEL authors="artem.troshkin"
WORKDIR /code/
COPY requirements.txt /code/
COPY . /code/

RUN pip install --no-cache-dir -r requirements.txt && \
    apt-get update -y && \
    apt-get install -y curl && \
    alembic upgrade head

CMD ["python", "bot_main.py"]