version: '3'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/code/logs/
    env_file:
      - .env
    network_mode: "bridge"